# Generated by Django 6.0.4 on 2026-04-26 02:32

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='name')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='name')),
                ('title_uz', models.CharField(max_length=200, null=True, verbose_name='name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('country', models.CharField(max_length=120, verbose_name='country')),
                ('country_en', models.CharField(max_length=120, null=True, verbose_name='country')),
                ('country_uz', models.CharField(max_length=120, null=True, verbose_name='country')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='city')),
                ('city_en', models.CharField(blank=True, max_length=120, null=True, verbose_name='city')),
                ('city_uz', models.CharField(blank=True, max_length=120, null=True, verbose_name='city')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='short description')),
                ('description_en', models.TextField(blank=True, max_length=500, null=True, verbose_name='short description')),
                ('description_uz', models.TextField(blank=True, max_length=500, null=True, verbose_name='short description')),
                ('body', models.TextField(help_text='Markdown is supported.', verbose_name='body')),
                ('body_en', models.TextField(help_text='Markdown is supported.', null=True, verbose_name='body')),
                ('body_uz', models.TextField(help_text='Markdown is supported.', null=True, verbose_name='body')),
                ('cover_image', models.ImageField(upload_to='universities/', verbose_name='cover image')),
                ('programs_offered', models.TextField(blank=True, help_text="Markdown list, e.g. '- Computer Science\\n- Economics'", verbose_name='programs offered')),
                ('programs_offered_en', models.TextField(blank=True, help_text="Markdown list, e.g. '- Computer Science\\n- Economics'", null=True, verbose_name='programs offered')),
                ('programs_offered_uz', models.TextField(blank=True, help_text="Markdown list, e.g. '- Computer Science\\n- Economics'", null=True, verbose_name='programs offered')),
                ('tuition_from', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='tuition from (per year)')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('UZS', 'UZS')], default='USD', max_length=3, verbose_name='currency')),
                ('world_ranking', models.PositiveIntegerField(blank=True, null=True, verbose_name='world ranking')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'university',
                'verbose_name_plural': 'universities',
                'ordering': ('order', 'world_ranking', 'title'),
            },
        ),
    ]
