# Generated by Django 6.0.4 on 2026-04-26 02:28

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('title_uz', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('destination', models.CharField(max_length=200, verbose_name='destination')),
                ('destination_en', models.CharField(max_length=200, null=True, verbose_name='destination')),
                ('destination_uz', models.CharField(max_length=200, null=True, verbose_name='destination')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='short description')),
                ('description_en', models.TextField(blank=True, max_length=500, null=True, verbose_name='short description')),
                ('description_uz', models.TextField(blank=True, max_length=500, null=True, verbose_name='short description')),
                ('body', models.TextField(help_text='Markdown is supported.', verbose_name='body')),
                ('body_en', models.TextField(help_text='Markdown is supported.', null=True, verbose_name='body')),
                ('body_uz', models.TextField(help_text='Markdown is supported.', null=True, verbose_name='body')),
                ('cover_image', models.ImageField(upload_to='tour-packages/', verbose_name='cover image')),
                ('duration_days', models.PositiveIntegerField(default=0, verbose_name='duration in days')),
                ('price_from', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='price from')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('UZS', 'UZS')], default='USD', max_length=3, verbose_name='currency')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated, e.g. beach,culture,adventure', max_length=200, verbose_name='tags')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'tour package',
                'verbose_name_plural': 'tour packages',
                'ordering': ('order', '-created_at'),
            },
        ),
    ]
