# Generated by Django 6.0.4 on 2026-04-26 01:32

import autoslug.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('title_uz', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('category', models.CharField(choices=[('general', 'General'), ('tourism', 'Tourism'), ('study', 'Study'), ('work', 'Work'), ('visa', 'Visa')], db_index=True, default='general', max_length=16, verbose_name='category')),
                ('excerpt', models.TextField(blank=True, help_text='Short summary shown in cards. Plain text only.', max_length=300, verbose_name='excerpt')),
                ('excerpt_en', models.TextField(blank=True, help_text='Short summary shown in cards. Plain text only.', max_length=300, null=True, verbose_name='excerpt')),
                ('excerpt_uz', models.TextField(blank=True, help_text='Short summary shown in cards. Plain text only.', max_length=300, null=True, verbose_name='excerpt')),
                ('body', models.TextField(help_text='Markdown is supported.', verbose_name='body')),
                ('body_en', models.TextField(help_text='Markdown is supported.', null=True, verbose_name='body')),
                ('body_uz', models.TextField(help_text='Markdown is supported.', null=True, verbose_name='body')),
                ('cover_image', models.ImageField(upload_to='blog/', verbose_name='cover image')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='published')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='published at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'blog post',
                'verbose_name_plural': 'blog posts',
                'ordering': ('-published_at', '-created_at'),
            },
        ),
    ]
