# Generated by Django 6.0.4 on 2026-04-26 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_ws_seen',
            field=models.DateTimeField(blank=True, help_text="Updated when the user's websocket connection is active.", null=True, verbose_name='last websocket seen'),
        ),
    ]
