# Generated by Django 6.0.4 on 2026-04-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=120, verbose_name='author name')),
                ('author_city', models.CharField(blank=True, max_length=120, verbose_name='author city')),
                ('author_photo', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='author photo')),
                ('body', models.TextField(help_text='Markdown is supported. Use **text** for bold.', verbose_name='body')),
                ('body_en', models.TextField(help_text='Markdown is supported. Use **text** for bold.', null=True, verbose_name='body')),
                ('body_uz', models.TextField(help_text='Markdown is supported. Use **text** for bold.', null=True, verbose_name='body')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'testimonial',
                'verbose_name_plural': 'testimonials',
                'ordering': ('order', '-created_at'),
            },
        ),
    ]
