# Generated by Django 6.0.4 on 2026-04-26 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='full name')),
                ('contact', models.CharField(help_text='User-provided email address or phone number.', max_length=120, verbose_name='email or phone')),
                ('service_type', models.CharField(choices=[('tourism', 'Tourism'), ('study', 'Study'), ('work', 'Work'), ('visa', 'Visa Support'), ('other', 'Other')], default='other', max_length=16, verbose_name='service type')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], db_index=True, default='new', max_length=16, verbose_name='status')),
                ('locale', models.CharField(blank=True, max_length=8, verbose_name='submitted in language')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'contact inquiry',
                'verbose_name_plural': 'contact inquiries',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PartnershipInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='company name')),
                ('contact', models.CharField(max_length=120, verbose_name='email or phone')),
                ('goals', models.TextField(verbose_name='goals and expectations')),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('closed', 'Closed')], db_index=True, default='new', max_length=16, verbose_name='status')),
                ('locale', models.CharField(blank=True, max_length=8, verbose_name='submitted in language')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'partnership inquiry',
                'verbose_name_plural': 'partnership inquiries',
                'ordering': ('-created_at',),
            },
        ),
    ]
