# Generated by Django 6.0.4 on 2026-04-26 02:36

import autoslug.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('title_uz', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('country', models.CharField(max_length=120, verbose_name='destination country')),
                ('country_en', models.CharField(max_length=120, null=True, verbose_name='destination country')),
                ('country_uz', models.CharField(max_length=120, null=True, verbose_name='destination country')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='short description')),
                ('description_en', models.TextField(blank=True, max_length=500, null=True, verbose_name='short description')),
                ('description_uz', models.TextField(blank=True, max_length=500, null=True, verbose_name='short description')),
                ('body', models.TextField(help_text='Markdown is supported.', verbose_name='body')),
                ('body_en', models.TextField(help_text='Markdown is supported.', null=True, verbose_name='body')),
                ('body_uz', models.TextField(help_text='Markdown is supported.', null=True, verbose_name='body')),
                ('cover_image', models.ImageField(upload_to='visa-types/', verbose_name='cover image')),
                ('processing_time', models.CharField(blank=True, help_text="Free text, e.g. '4-6 weeks'", max_length=120, verbose_name='processing time')),
                ('processing_time_en', models.CharField(blank=True, help_text="Free text, e.g. '4-6 weeks'", max_length=120, null=True, verbose_name='processing time')),
                ('processing_time_uz', models.CharField(blank=True, help_text="Free text, e.g. '4-6 weeks'", max_length=120, null=True, verbose_name='processing time')),
                ('success_rate', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='success rate (%)')),
                ('category', models.CharField(choices=[('tourist', 'Tourist'), ('student', 'Student'), ('work', 'Work'), ('business', 'Business'), ('family', 'Family')], db_index=True, default='tourist', max_length=16, verbose_name='category')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'visa type',
                'verbose_name_plural': 'visa types',
                'ordering': ('order', 'country', 'title'),
            },
        ),
    ]
