# Generated by Django 6.0.4 on 2026-04-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('role', models.CharField(max_length=120, verbose_name='role')),
                ('role_en', models.CharField(max_length=120, null=True, verbose_name='role')),
                ('role_uz', models.CharField(max_length=120, null=True, verbose_name='role')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='photo')),
                ('bio', models.TextField(blank=True, verbose_name='bio')),
                ('bio_en', models.TextField(blank=True, null=True, verbose_name='bio')),
                ('bio_uz', models.TextField(blank=True, null=True, verbose_name='bio')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'team member',
                'verbose_name_plural': 'team members',
                'ordering': ('order', 'id'),
            },
        ),
    ]
