# Generated by Django 6.0.4 on 2026-04-26 02:34

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('title_uz', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('country', models.CharField(max_length=120, verbose_name='country')),
                ('country_en', models.CharField(max_length=120, null=True, verbose_name='country')),
                ('country_uz', models.CharField(max_length=120, null=True, verbose_name='country')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='city')),
                ('city_en', models.CharField(blank=True, max_length=120, null=True, verbose_name='city')),
                ('city_uz', models.CharField(blank=True, max_length=120, null=True, verbose_name='city')),
                ('industry', models.CharField(blank=True, max_length=120, verbose_name='industry')),
                ('industry_en', models.CharField(blank=True, max_length=120, null=True, verbose_name='industry')),
                ('industry_uz', models.CharField(blank=True, max_length=120, null=True, verbose_name='industry')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='short description')),
                ('description_en', models.TextField(blank=True, max_length=500, null=True, verbose_name='short description')),
                ('description_uz', models.TextField(blank=True, max_length=500, null=True, verbose_name='short description')),
                ('body', models.TextField(help_text='Markdown is supported.', verbose_name='body')),
                ('body_en', models.TextField(help_text='Markdown is supported.', null=True, verbose_name='body')),
                ('body_uz', models.TextField(help_text='Markdown is supported.', null=True, verbose_name='body')),
                ('cover_image', models.ImageField(upload_to='jobs/', verbose_name='cover image')),
                ('salary_from', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='salary from')),
                ('salary_to', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='salary to')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('UZS', 'UZS')], default='USD', max_length=3, verbose_name='currency')),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship')], db_index=True, default='full_time', max_length=16, verbose_name='employment type')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'job',
                'verbose_name_plural': 'jobs',
                'ordering': ('order', '-created_at'),
            },
        ),
    ]
