# Generated by Django 6.0.4 on 2026-04-26 03:03

import apps.applications.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('service_type', models.CharField(choices=[('tourism', 'Tourism'), ('study', 'Study'), ('work', 'Work'), ('visa', 'Visa')], db_index=True, max_length=16, verbose_name='service type')),
                ('target_slug', models.CharField(blank=True, help_text="Slug of the target catalog item (e.g. 'mit', 'bali-cultural-adventure').", max_length=255, verbose_name='target item slug')),
                ('target_label', models.CharField(blank=True, help_text='Human-readable label cached at submission time.', max_length=255, verbose_name='target item label')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_review', 'In Review'), ('needs_info', 'Needs Info'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('closed', 'Closed')], db_index=True, default='draft', max_length=16, verbose_name='status')),
                ('current_step', models.PositiveSmallIntegerField(default=1, help_text='Highest step the user has reached in the multi-step form.', verbose_name='current step')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Per-service form fields. Schema varies by service_type.', verbose_name='application data')),
                ('internal_notes', models.TextField(blank=True, help_text='Notes from staff. Not shown to the user.', verbose_name='internal notes')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='submitted at')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='decided at')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'application',
                'verbose_name_plural': 'applications',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('passport', 'Passport'), ('transcript', 'Transcript'), ('cv', 'CV / Resume'), ('financial', 'Financial statement'), ('certificate', 'Certificate'), ('photo', 'Photo'), ('other', 'Other')], default='other', max_length=16, verbose_name='kind')),
                ('file', models.FileField(upload_to=apps.applications.models.document_upload_path, verbose_name='file')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='original filename')),
                ('size_bytes', models.PositiveBigIntegerField(default=0, verbose_name='size (bytes)')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verified at')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.application')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'ordering': ('-uploaded_at',),
            },
        ),
    ]
