# Generated by Django 6.0.4 on 2026-04-26 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='team_message',
            field=models.TextField(blank=True, help_text='Message visible to the user. Use for status updates, requests for more info, etc.', verbose_name='message to user'),
        ),
    ]
