# Generated by Django 6.0.4 on 2026-04-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_team_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='last_notified_status',
            field=models.CharField(blank=True, default='', help_text='Tracks the last status the user was emailed about. Internal.', max_length=16, verbose_name='last notified status'),
        ),
        migrations.AddField(
            model_name='application',
            name='last_notified_team_message',
            field=models.TextField(blank=True, default='', help_text='Tracks the last team_message the user was emailed about. Internal.', verbose_name='last notified team message'),
        ),
    ]
