# Generated by Django 6.0.4 on 2026-04-26 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('general', 'General'), ('tourism', 'Tourism'), ('study', 'Study'), ('work', 'Work'), ('visa', 'Visa')], db_index=True, default='general', max_length=16, verbose_name='category')),
                ('question', models.CharField(max_length=255, verbose_name='question')),
                ('question_en', models.CharField(max_length=255, null=True, verbose_name='question')),
                ('question_uz', models.CharField(max_length=255, null=True, verbose_name='question')),
                ('answer', models.TextField(help_text='Markdown is supported.', verbose_name='answer')),
                ('answer_en', models.TextField(help_text='Markdown is supported.', null=True, verbose_name='answer')),
                ('answer_uz', models.TextField(help_text='Markdown is supported.', null=True, verbose_name='answer')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ('category', 'order', 'id'),
            },
        ),
    ]
